### ISSUE TITLE
import destruction from cjs modules

### ISSUE THREAD

**Issue by aliai** [hqjs/hq#1]
Using react@16.4.0:

```js
import React, { Component } from "react";
```

will result into
```js
import * as _ref from "https://localhost:8080/node_modules/react";

const {
  Component
} = _ref;
```

which is incorrect since, `react` exports itself as `default` in the module and therefore `* as _ref` will give you `_ref.default` and `_ref.default.Component` and not `_ref.Component`.

**Comment by hqjs** [comment]
Thanks for a feedback! We will investigate if it is the case for other packages and older react versions as well. For now you can just import `React` and use `React.Component` or destructure it separately from import.

**Comment by hqjs** [comment]
Please use `import { React as default, Component } from "react";` that is working now.
