### ISSUE TITLE
Proxy requests for non static files.

### ISSUE THREAD

**Issue by JoyceBabu** [hqjs/hq#12]
Is it possible to proxy requests to a backend, when the file cannot be served by hq?

For example, I would like to proxy requests for PHP files to Apache server.

**Comment by hqjs** [comment]
Hi @JoyceBabu, It is not possible at the moment. I will think how it can be achieved without configuration. Please share your ideas if you have them in mind.

For now, of course, it is possible to configure nginx to proxy to either hq or php, but it is extra effort.

**Comment by hqjs** [comment]
Closing as it can be configured trough APACHE routing.
