### ISSUE TITLE
Installation fail on both window & docker container

### ISSUE THREAD

**Issue by sesameguy** [hqjs/hq#13]
`npm install -g @hqjs/hq` shows below error:
```console
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-23T06_22_21_599Z-debug.log
```
node ver: `14.0.0`
test env:
- `windows 10 pro ver 1909`
- `node:buster (docker image)`

**Comment by hqjs** [comment]
Hi @sesameguy, thanks for reporting an issue. People say installation in docker might work with `yarn`, please give it a try. As for windows - I can't really test it (only have mac), but it looks like it is a problem with `node-sass`, not `hq`.

I will double check compatibility with `node@14` and check if there are any related installation problem with `node-sass`.

**Comment by sesameguy** [comment]
thx, it works in docker container with `yarn`
