### ISSUE TITLE
Installation fail

### ISSUE THREAD

**Issue by JoshuaAmaju** [hqjs/hq#14]
The installation fails when trying to install `babel-plugin-minify-dead-code-elimination` on windows

![Annotation 2020-05-13 114716](https://user-images.githubusercontent.com/13833975/81803407-8ebcb000-950f-11ea-9a53-d2df332039b9.jpg)

**Comment by liqi0816** [comment]
https://www.npmjs.com/package/babel-plugin-minify-dead-code-elimination/v/0.5.1

Guess it is a temporary network issue?

**Comment by hqjs** [comment]
Yeah, I can't reproduce, either. @JoshuaAmaju have you succeed with the installation?

**Comment by JoshuaAmaju** [comment]
Yes, it was just a network issue like you said. Sorry, Thanks
