### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by reob-info** [hqjs/hq#16]
Please, add support to GNOME WEB as default browser.
Thanks.

**Comment by hqjs** [comment]
Can you please post user agent string for this browser? Do you know by chance since which version it supports ES modules?

To get user agent string:
1. Open your browser
2. Open browser console
3. type `navigator.userAgent`

**Comment by hqjs** [comment]
@reob-info any updates regarding this issue?

**Comment by hqjs** [comment]
Closed because of inactivity.
