### ISSUE TITLE
HTTPS/2 Issues

### ISSUE THREAD

**Issue by Zageron** [hqjs/hq#22]
Do you have a guide on how this works?
I have the certs in the right place, but my browser returns this error when trying to open as https
`An error occurred during a connection to 172.25.7.63:8080. PR_END_OF_FILE_ERROR`

The extension says it should start in https mode automatically, so the Go Live section listing as `http://172.25.7.63:8080/` might be an issue?

Curl
``` zsh
❯ curl -k https://172.25.7.63:8080
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```
this error is indicative of the web server not supporting ssl?

Certs were generated in WSL by mkcert using a hostfile mapping to the IP that hq spits out.

**Comment by hqjs** [comment]
Thanks for reporting. That might be some regression that I missed. Command line suppose to show invitation to `https`. I'll take a look.

**Comment by hqjs** [comment]
Found regression during refactoring. Will fix in the next version together with other changes.

**Comment by hqjs** [comment]
Please check if it is working for you with `@hqjs/hq@0.0.22`. Please note that you can put certificates in any place, server should be able to find them if they are in `.pem` format and key file name should ends with `key.pem`

**Comment by Zageron** [comment]
This fixed my https woes! Thank you. :)
