### ISSUE TITLE
Live Reload, or Rebuild, doesn't work with WSL

### ISSUE THREAD

**Issue by Zageron** [hqjs/hq#23]
Go Live or `hq` doesn't actually rebuild the project when making changes and saving.

- Is any output supposed to show up after hq announce when saving files? I get no output.

``` zsh
❯ hq
(c) hqjs @ 0.0.21
Start time: 0.1 s

Visit http://localhost:8081
or http://172.25.7.63:8081 within local network
```

**Comment by hqjs** [comment]
You can try to run it like this `hq --verbose` for debugging. Livereload script attaches to `index.html` file. If you don't have it - you can try to install separate Live reload plugin for a browser.

**Comment by Zageron** [comment]
So I am running in verbose now, thanks for that. I get all of the outputs on first opening.

My folder structure is effectively:
src
  index.html
  index.ts

- Launch hq, open in browser.
- full set of build stats, etag, and resolves for everything.
- Make a change in index.html or index.ts
- No output from HQ.
- Refresh the webpage.
- All output lists `version 0 - 304 Not Modified`

Here's the repository: https://github.com/zageron/zux

**Comment by Zageron** [comment]
![image](https://user-images.githubusercontent.com/1892473/92669273-eaccf080-f2c5-11ea-8066-1532dc63ffb5.png)

**Comment by hqjs** [comment]
If you have `index.html` it should work out of the box. `hq` listens for fs changes with `chokidar`, if version is not changing - that means change events are being lost. That should be something WSL specific, may be some problems with chokidar.

**Comment by hqjs** [comment]
Without WSL it works without any problems. I can't test WSL so may be it is worth to post an issue to chokidar repository.

**Comment by Zageron** [comment]
Yeah so I installed node on windows and switched out of wsl, works now. Interestingly, HTTPS stopped working. (.22)

Anyway I will probably stop fiddling with this and just work on my project. This tool absolutely simplifies everything so I am very pleased. Thanks for making this. :)

**Comment by Zageron** [comment]
This issue is caused by using the windows mounted drives in WSL. This is a known issue.
Easy workaround, clone into ~ instead of /mnt/some/windows/folder

https://github.com/microsoft/WSL/issues/4417

**Comment by stackchain** [comment]
It is cloned into ~ and still not working.
