### ISSUE TITLE
Using a proxy in Angular with hqjs

### ISSUE THREAD

**Issue by azaeng04** [hqjs/hq#26]
Our app currently uses a proxy to connect to backend services.
Is it possible to somehow configure this as part of hqjs?
Cos at the moment I would still need to do a `ng serve -c proxy`

**Comment by hqjs** [comment]
Thanks for reporting. It is not possible as `hq` was designed not to require any configuration. I will think how to make it possible, probably some external package that does it will help.

**Comment by hqjs** [comment]
@azaeng04 give a try to https://www.npmjs.com/package/http-proxy-cli it seems like what you need, you can run both hq and backend and redirect requests from proxy to both of them.
