### ISSUE TITLE
npm link doesn't function as expected

### ISSUE THREAD

**Issue by Zageron** [hqjs/hq#28]
```js
///resolve-path.mjs
resolveVendor
    const srcPath = await resolvePackageFrom(ctx.app.root, ctx.dpath, ctx.app.hqroot);
    ctx.srcPath = await fs.realpath(srcPath);
    const stats = await fs.lstat(ctx.srcPath);
    ctx.size = stats.size;
    ctx.dpath = getModulePath(ctx.srcPath);
    ctx.dirname = path.dirname(ctx.dpath);

// utils.mjs
export const getModulePath = filepath => {
  const parts = pathToURL(filepath).split('/node_modules/');
  return `/node_modules/${parts[parts.length - 1]}`;
};
```

ctx.app.root: '/home/zageron/git/zux'
ctx.dpath: '/node_modules//home/zageron/git/rust/ffrust/pkg/ffrust.js'
ctx.srcPath: '/home/zageron/git/rust/ffrust/pkg/ffrust.js'

Actual path with link: '/home/zageron/git/zux/node_modules/ffrust/ffrust.js'

The path login in HQ is very hard to understand, and I doubt I would be able to resolve this without breaking a lot.

The package.json entry is
```
    "ffrust": "file:../rust/ffrust/pkg",
```

I used `npm link` in ffrust root.
and `npm link ffrust` in zux root.

Thanks!

**Comment by hqjs** [comment]
Thanks for reporting! Where this section come from
```json
{
  "ffrust": "file:../rust/ffrust/pkg"
}
```
is it from `browser` field of `package.json`? Link by itself should work, but I did not test it with browser spec

**Comment by Zageron** [comment]
It's just the package dependencies.
```json

"devDependencies": {
    "ffrust": "file:../pkg",
  }
```

**Comment by hqjs** [comment]
Not sure if `resolve` supports such a form. I would appreciate if you can setup minimal example to play with.
