### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Venryx** [hqjs/hq#31]
I know the website says "Looking for documentation? You don't need it!", but this is just not acceptable for many readers (including myself).

While the first steps of trying out hq may indeed not require documentation, it's still important to have available for the people who want to understand the overall design of the system, for them to evaluate whether it's designed well.

As it stands, even if hq works out of the box, I lack confidence in it because I don't have enough information to confirm that it's "built well enough" to be robust/flexible for future needs.

It is of course ultimately up to you, but I highly recommend at least having some high-level documentation about the design philosophies, decisions made on the various challenges (and how hq's decisions were different than Webpack, Snowpack, etc.), and a list of advantages and disadvantages of the design approach hq chose to take.

For now I'm going with Snowpack (since it seems to be similar and has more documentation), but hq gaining documentation would definitely interest me in giving hq a closer look.

(Feel free to close this thread of course, if it's not considered worthwhile at this point, or is not specific enough.)

**Comment by yuri-karadzhov** [comment]
The website also answers your questions in the paragraphs above. It says why hq was created (way before snowpack) - to avoid bundling and speed up development, and how it is architectured - checks file extension and user agent to determine your browser capabilities, then use babel, postcss and posthtml to compile code on the fly. It also states the main philosophy - not to create another tool but act as a polyfill that you can replace with regular static server as soon as the code that you write matches current version of the specification. There are no plugins for hq as well as there is no configuration, you are supposed to write plugins for babel, postcss and posthtml, that you can use in any other project including [bla]pack, that makes your free of lock on specific tool. Hq is just a simple server/build tool that makes your code work using babel, postcss and posthtml.

Am I missing something else?

**Comment by Venryx** [comment]
I've read that, but it doesn't go into enough detail for me to properly assess its design quality and compare it with the other tools.

To be clear, I'm not saying the tool is unusable as it stands, just making the note that additional documentation will open it up to a wider potential userbase (ie. people who see a lack of documentation as an issue).

(If you're one of the maintainers, feel free to close this issue, as it was meant more as a note than an active issue.)

**Comment by yuri-karadzhov** [comment]
Thanks for the advice. It might worth to add a diagram of the request and may be some more details on standard plugins being used and transformation that are made (these info is being spread between plugins and require some effort to find). A copy-paste examples might be handy as well.

The biggest problem of this tool is lack of PR comparing to snowpack and others who scream very loud and state they are the best and the first even if they are not. Another pair of hands are very appreciated.

Talking about documentation section - it states that there are no own configuration and the only thing you can configure are modules for babel, postcss and posthtml that can be then reused in any other project.

I'll close it for now, but will work on some better intro for the website.
